CREATE TABLE IF NOT EXISTS `swm_third_api_log` (
  `id` varchar(64) NOT NULL COMMENT '主键',
  `business_type` varchar(50) DEFAULT NULL COMMENT '业务类型：person-人员，device-设备，beacon-信标',
  `http_method` varchar(20) DEFAULT NULL COMMENT '请求方式',
  `request_url` varchar(1000) DEFAULT NULL COMMENT '接口地址',
  `request_param` longtext COMMENT '请求参数',
  `response_param` longtext COMMENT '返回参数',
  `request_time` datetime DEFAULT NULL COMMENT '请求时间',
  `response_time` datetime DEFAULT NULL COMMENT '响应时间',
  `duration` bigint DEFAULT NULL COMMENT '接口耗时（毫秒）',
  `http_status` int DEFAULT NULL COMMENT 'HTTP状态码',
  `execute_status` char(1) DEFAULT NULL COMMENT '执行状态：1-成功，0-失败',
  `exception_info` text COMMENT '异常信息',
  `status` char(1) DEFAULT '0' COMMENT '状态',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_date` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_date` datetime DEFAULT NULL COMMENT '更新时间',
  `remarks` varchar(500) DEFAULT NULL COMMENT '备注信息',
  `corp_code` varchar(64) DEFAULT NULL COMMENT '租户编码',
  `corp_name` varchar(200) DEFAULT NULL COMMENT '租户名称',
  PRIMARY KEY (`id`),
  KEY `idx_swm_third_api_log_business_type` (`business_type`),
  KEY `idx_swm_third_api_log_request_time` (`request_time`),
  KEY `idx_swm_third_api_log_execute_status` (`execute_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='第三方接口调用日志表';
