-- swm_person 人员登记表
ALTER TABLE swm_person
    ADD dept VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '部门' AFTER job_type;

ALTER TABLE swm_person
    ADD position VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '职务' AFTER dept;


#  ==================== 字典 ==============================
# 人员和职务字典
INSERT INTO `swm`.`js_sys_dict_type` (`id`, `dict_name`, `dict_type`, `is_sys`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`) VALUES ('1985241273990819840', '安全帽-部门', 'swm_dept', '1', '0', 'system', '2025-11-03 15:02:58', 'system', '2025-11-03 15:02:58', NULL);
INSERT INTO `swm`.`js_sys_dict_type` (`id`, `dict_name`, `dict_type`, `is_sys`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`) VALUES ('1985241382396801024', '安全帽_职务', 'swm_position', '1', '0', 'system', '2025-11-03 15:03:24', 'system', '2025-11-03 15:06:56', NULL);

INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242615916441600', '0', '0,', 30, '0000000030,', '1', 0, '领导班子', '领导班子', 'swm_dept_01', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:08:18', 'system', '2025-11-03 15:08:18', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242693527842816', '0', '0,', 60, '0000000060,', '1', 0, '安全生产监督管理部', '安全生产监督管理部', 'swm_dept_02', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:08:37', 'system', '2025-11-03 15:08:37', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242719318618112', '0', '0,', 90, '0000000090,', '1', 0, '生产部', '生产部', 'swm_dept_03', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:08:43', 'system', '2025-11-03 15:08:43', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242743226150912', '0', '0,', 120, '0000000120,', '1', 0, '质量部', '质量部', 'swm_dept_04', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:08:49', 'system', '2025-11-03 15:08:49', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242764357054464', '0', '0,', 150, '0000000150,', '1', 0, '综合办公室', '综合办公室', 'swm_dept_05', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:08:54', 'system', '2025-11-03 15:08:54', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242783738933248', '0', '0,', 180, '0000000180,', '1', 0, '人力资源部', '人力资源部', 'swm_dept_06', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:08:58', 'system', '2025-11-03 15:08:58', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242805134077952', '0', '0,', 210, '0000000210,', '1', 0, '商务部', '商务部', 'swm_dept_07', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:09:03', 'system', '2025-11-03 15:09:03', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242826277564416', '0', '0,', 240, '0000000240,', '1', 0, '技术部', '技术部', 'swm_dept_08', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:09:08', 'system', '2025-11-03 15:09:08', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242846590578688', '0', '0,', 270, '0000000270,', '1', 0, '财务部', '财务部', 'swm_dept_09', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:09:13', 'system', '2025-11-03 15:09:13', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242869583753216', '0', '0,', 300, '0000000300,', '1', 0, '市场部', '市场部', 'swm_dept_10', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:09:19', 'system', '2025-11-03 15:09:19', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985242891058589696', '0', '0,', 330, '0000000330,', '1', 0, '客户', '客户', 'swm_dept_11', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:09:24', 'system', '2025-11-03 15:09:24', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244522793840640', '0', '0,', 360, '0000000360,', '1', 0, '制造专班-生产组', '制造专班-生产组', 'swm_dept_12', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:15:53', 'system', '2025-11-03 15:15:53', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244568822132736', '0', '0,', 390, '0000000390,', '1', 0, '制造专班-技术组', '制造专班-技术组', 'swm_dept_13', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:16:04', 'system', '2025-11-03 15:16:04', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244603584524288', '0', '0,', 420, '0000000420,', '1', 0, '制造专班-质量组', '制造专班-质量组', 'swm_dept_14', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:16:12', 'system', '2025-11-03 15:16:12', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244642813849600', '0', '0,', 450, '0000000450,', '1', 0, '制造专班-商务组', '制造专班-商务组', 'swm_dept_15', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:16:22', 'system', '2025-11-03 15:16:22', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244682198364160', '0', '0,', 480, '0000000480,', '1', 0, '制造专班-安监组', '制造专班-安监组', 'swm_dept_16', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:16:31', 'system', '2025-11-03 15:16:31', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244718437150720', '0', '0,', 510, '0000000510,', '1', 0, '制造专班-一车间', '制造专班-一车间', 'swm_dept_17', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:16:40', 'system', '2025-11-03 15:16:40', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244754201980928', '0', '0,', 540, '0000000540,', '1', 0, '制造专班-二车间', '制造专班-二车间', 'swm_dept_18', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:16:48', 'system', '2025-11-03 15:16:48', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985244804432965632', '0', '0,', 570, '0000000570,', '1', 0, '制造专班-桥梁车间', '制造专班-桥梁车间', 'swm_dept_19', NULL, 'swm_dept', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:17:00', 'system', '2025-11-03 15:17:00', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245355291881472', '0', '0,', 30, '0000000030,', '1', 0, '总经理', '总经理', 'swm_position_01', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:11', 'system', '2025-11-03 15:19:11', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245377567830016', '0', '0,', 60, '0000000060,', '1', 0, '党委副书记', '党委副书记', 'swm_position_02', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:17', 'system', '2025-11-03 15:19:17', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245403694149632', '0', '0,', 90, '0000000090,', '1', 0, '副总经理', '副总经理', 'swm_position_03', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:23', 'system', '2025-11-03 15:19:23', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245424749555712', '0', '0,', 120, '0000000120,', '1', 0, '副总经理', '副总经理', 'swm_position_04', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:28', 'system', '2025-11-03 15:19:28', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245450938789888', '0', '0,', 150, '0000000150,', '1', 0, '总会计师', '总会计师', 'swm_position_05', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:34', 'system', '2025-11-03 15:19:34', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245473688694784', '0', '0,', 180, '0000000180,', '1', 0, '总工程师', '总工程师', 'swm_position_06', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:40', 'system', '2025-11-03 15:19:40', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245495515852800', '0', '0,', 210, '0000000210,', '1', 0, '副总工程师', '副总工程师', 'swm_position_07', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:45', 'system', '2025-11-03 15:19:45', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245518148317184', '0', '0,', 240, '0000000240,', '1', 0, '安全总监', '安全总监', 'swm_position_08', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:50', 'system', '2025-11-03 15:19:50', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `swm`.`js_sys_dict_data` (`dict_code`, `parent_code`, `parent_codes`, `tree_sort`, `tree_sorts`, `tree_leaf`, `tree_level`, `tree_names`, `dict_label`, `dict_value`, `dict_icon`, `dict_type`, `is_sys`, `description`, `css_style`, `css_class`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `extend_s1`, `extend_s2`, `extend_s3`, `extend_s4`, `extend_s5`, `extend_s6`, `extend_s7`, `extend_s8`, `extend_i1`, `extend_i2`, `extend_i3`, `extend_i4`, `extend_f1`, `extend_f2`, `extend_f3`, `extend_f4`, `extend_d1`, `extend_d2`, `extend_d3`, `extend_d4`, `extend_json`) VALUES ('1985245541703528448', '0', '0,', 270, '0000000270,', '1', 0, '厂长', '厂长', 'swm_position_09', NULL, 'swm_position', '1', NULL, NULL, NULL, '0', 'system', '2025-11-03 15:19:56', 'system', '2025-11-03 15:19:56', NULL, '0', 'Jessite', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


# 危险源管理  增加是否报警标记
ALTER TABLE swm_hazard_source
    ADD filter_identity_card TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '白名单人员（这里的人员不收到报警信号）' AFTER beacon_tag;
ALTER TABLE swm_hazard_source
    ADD filter_personnel TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '白名单人员（这里的人员不收到报警信号）' AFTER filter_identity_card;


-- 日考勤统计表实体类
ALTER TABLE swm_daily_attendance
    ADD pending_clock_out_compensate BOOLEAN NOT NULL DEFAULT FALSE COMMENT '当天该员工是否已经触发过补偿且未恢复，true = 已补卡' AFTER clock_out_date;

# 人员增加人员编码、年龄、.紧急联系人、紧急联系人手机号
ALTER TABLE swm_person
    ADD person_number VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '人员编码' AFTER name;
ALTER TABLE swm_person
    ADD age VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '年龄' AFTER person_number;
ALTER TABLE swm_person
    ADD urgent_person VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '紧急联系人' AFTER phone_number;
ALTER TABLE swm_person
    ADD urgent_phone_number VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '紧急联系人手机号' AFTER urgent_person;

# 三车间
INSERT INTO `fms_position_archive` (`id`, `position_name`, `region`, `type`, `project_id`, `description`, `status`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `map_location`, `manufacturing_type`, `handover_person`, `telephone`, `position_code`, `parent_code`, `install_restrict`, `dept_code`, `dept_name`, `sync_energy_system`, `ts`, `bar_code`) VALUES ('17750732355353313', '三车间', '0001A110000000002ZWA', 'CJ', '1001A110000000002FEK', NULL, '0', 'ZJGG_adminZJGG', '2024-04-02 16:10:13', 'ZJGG_adminZJGG', '2024-04-02 16:10:13', NULL, 'ZJGG', '中建钢构股份有限公司', NULL, 'NBZZ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `fms_prod_line` (`id`, `prod_line_name`, `prod_line_code`, `head_id`, `head_name`, `work_shop_id`, `work_shop_name`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `make_unit`) VALUES ('1775075288571641856', '三车间桥梁线', 'GD_CJ3_QL', '13961023384', NULL, '17750732355353313', NULL, 'ZJGG_adminZJGG', '2024-04-02 16:18:23', 'ZJGG_adminZJGG', '2024-04-02 16:18:23', NULL, 'ZJGG', '中建钢构股份有限公司', '0001A110000000002ZWA');
INSERT INTO `fms_work_group` (`id`, `work_group_name`, `work_group_code`, `head_id`, `prod_line_id`, `work_shop_id`, `proc_id`, `create_by`, `create_date`, `update_by`, `update_date`, `remarks`, `corp_code`, `corp_name`, `make_unit`, `work_shop_name`, `office_work_code`) VALUES ('17750853342652661', '三车间桥梁线', 'GDBZ_LBQLLW', '', '1775075288571641856', '1775073235535331328', NULL, 'ZJGG_adminZJGG', '2024-04-02 16:58:18', 'ZJGG_adminZJGG', '2024-04-02 16:58:18', NULL, 'ZJGG', '中建钢构股份有限公司', '0001A110000000002ZWA', NULL, NULL);

# 增加脱帽报警时间间隔
ALTER TABLE swm_helmet_device_config
    ADD hat_off_alarm_interval VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '脱帽报警时间间隔' AFTER beacon_filter_name;