<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.jeesite</groupId>
		<artifactId>jeesite-cloud-parent</artifactId>
		<version>5.0.1-SNAPSHOT</version>
		<relativePath/>
	</parent>
	
	<artifactId>jeesite-cloud-module-swm-client</artifactId>
	<packaging>jar</packaging>
	<version>5.0.1-SNAPSHOT</version>
	
	<name>JeeSite Cloud Module Swm Client</name>
	<url>http://jeesite.com</url>
	<inceptionYear>2013-Now</inceptionYear>
	
	<properties>
		
	</properties>
	
	<dependencies>
		
		<!-- 云客户端 -->
		<dependency>
			<groupId>com.jeesite</groupId>
			<artifactId>jeesite-cloud-framework</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>com.jeesite</groupId>
			<artifactId>jeesite-cloud-module-bpm-client</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.jeesite</groupId>
			<artifactId>jeesite-cloud-module-fms-client</artifactId>
			<version>5.0.1-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
	<distributionManagement>
		<repository>
			<!--            这个ID就是刚才setting.xml文件中的id -->
			<id>cscec-repos</id>
			<url>http://10.50.103.163:8081/nexus/repository/maven-releases/</url>
		</repository>
		<!--        仓库的路径-->
		<snapshotRepository>
			<!--            这个ID就是刚才setting.xml文件中的id -->
			<id>cscec-repos</id>
			<url>http://10.50.103.163:8081/nexus/repository/maven-snapshots/</url>
		</snapshotRepository>
	</distributionManagement>
	<build>
		<plugins>
			
		</plugins>
	</build>
	
	<developers>  
		<developer>
			<id>thinkgem</id>
			<name>WangZhen</name>
			<email>thinkgem at 163.com</email>
			<roles><role>Project lead</role></roles>
			<timezone>+8</timezone>  
		</developer>
	</developers>
	
	<organization>
		<name>JeeSite</name>
		<url>http://jeesite.com</url>
	</organization>
	
</project>
