-- SWM 监控设备表迁移：保留 JeeSite 业务字段，租户隔离统一使用 tenant_id。
CREATE TABLE IF NOT EXISTS `js_sys_monitor_device_info` (
  `id` varchar(64) NOT NULL COMMENT '主键',
  `rec_type` varchar(20) DEFAULT NULL COMMENT '记录类型',
  `parent_id` varchar(64) DEFAULT NULL COMMENT '父节点 ID',
  `tree_sort` varchar(20) DEFAULT NULL COMMENT '树节点排序',
  `tree_leaf` char(1) DEFAULT NULL COMMENT '是否叶子节点',
  `parent_name` varchar(200) DEFAULT NULL COMMENT '父节点名称',
  `name` varchar(200) NOT NULL COMMENT '设备名称',
  `code` varchar(100) DEFAULT NULL COMMENT '设备编号',
  `device_type` varchar(50) DEFAULT NULL COMMENT '设备类型',
  `ip` varchar(64) DEFAULT NULL COMMENT '设备 IP 地址',
  `rtsp_port` varchar(20) DEFAULT NULL COMMENT 'RTSP 端口',
  `admin_user` varchar(100) DEFAULT NULL COMMENT '设备管理账号',
  `admin_password` varchar(200) DEFAULT NULL COMMENT '设备管理密码',
  `rtsp_uri` varchar(500) DEFAULT NULL COMMENT '设备资源路径',
  `channel` varchar(50) DEFAULT NULL COMMENT '直播通道',
  `subtype` varchar(50) DEFAULT NULL COMMENT '码流类型',
  `load_source` varchar(500) DEFAULT NULL COMMENT '加载地址',
  `stream_url` varchar(500) DEFAULT NULL COMMENT '直播流地址',
  `camera_index_code` varchar(100) DEFAULT NULL COMMENT '摄像机唯一标识',
  `status` char(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除状态：0 正常，1 删除',
  `remarks` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
  `update_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT 'RuoYi 租户 ID',
  PRIMARY KEY (`id`),
  KEY `idx_monitor_device_tenant_status` (`tenant_id`, `status`),
  KEY `idx_monitor_device_parent` (`parent_id`),
  KEY `idx_monitor_device_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SWM 监控设备信息';
